# Generated by Django 4.2.2 on 2023-07-10 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Order Summary',
                'verbose_name_plural': 'Orders Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('restaurant.order',),
        ),
    ]
